# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['formactionthrough'],
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'A short descriptive title.', max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FormActionThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Action')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Form')),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
        migrations.CreateModel(
            name='FormDataItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='formfactory.FormData')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'A short descriptive title.', max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('field_type', models.CharField(choices=[(b'BooleanField', b'BooleanField'), (b'CharField', b'CharField'), (b'ChoiceField', b'ChoiceField'), (b'DateField', b'DateField'), (b'DateTimeField', b'DateTimeField'), (b'DecimalField', b'DecimalField'), (b'EmailField', b'EmailField'), (b'FloatField', b'FloatField'), (b'GenericIPAddressField', b'GenericIPAddressField'), (b'IntegerField', b'IntegerField'), (b'MultipleChoiceField', b'MultipleChoiceField'), (b'SlugField', b'SlugField'), (b'SplitDateTimeField', b'SplitDateTimeField'), (b'TimeField', b'TimeField'), (b'URLField', b'URLField'), (b'UUIDField', b'UUIDField')], max_length=128)),
                ('initial', models.TextField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(default=256)),
                ('help_text', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.CharField(max_length=64)),
                ('placeholder', models.CharField(blank=True, max_length=128, null=True)),
                ('required', models.BooleanField(default=True)),
                ('disabled', models.BooleanField(default=False)),
                ('additional_validators', models.CharField(blank=True, max_length=128, null=True)),
                ('choices', models.ManyToManyField(to='formfactory.FieldChoice')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formfactory.Form')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='formdataitems',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.FormField'),
        ),
        migrations.AddField(
            model_name='form',
            name='actions',
            field=models.ManyToManyField(through='formfactory.FormActionThrough', to='formfactory.Action'),
        ),
    ]
