# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='failure_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='success_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
