# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='widget',
            field=models.CharField(blank=True, choices=[(b'TextInput', b'TextInput'), (b'NumberInput', b'NumberInput'), (b'EmailInput', b'EmailInput'), (b'URLInput', b'URLInput'), (b'PasswordInput', b'PasswordInput'), (b'HiddenInput', b'HiddenInput'), (b'DateInput', b'DateInput'), (b'DateTimeInput', b'DateTimeInput'), (b'TimeInput', b'TimeInput'), (b'Textarea', b'Textarea'), (b'CheckboxInput', b'CheckboxInput'), (b'Select', b'Select'), (b'NullBooleanSelect', b'NullBooleanSelect'), (b'SelectMultiple', b'SelectMultiple'), (b'RadioSelect', b'RadioSelect'), (b'CheckboxSelectMultiple', b'CheckboxSelectMultiple')], help_text=b'Leave blank if you would prefer to use the default widget.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[(b'formfactory.tests.actions.dummy_action', b'formfactory.tests.actions.dummy_action'), (b'formfactory.actions.login', b'formfactory.actions.login'), (b'formfactory.actions.send_email', b'formfactory.actions.send_email'), (b'formfactory.actions.store_data', b'formfactory.actions.store_data')], max_length=128),
        ),
    ]
