# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard',
            name='post_to',
        ),
        migrations.RemoveField(
            model_name='wizard',
            name='submit_button_text',
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[(b'formfactory.actions.login', b'formfactory.actions.login'), (b'formfactory.actions.send_email', b'formfactory.actions.send_email'), (b'formfactory.actions.store_data', b'formfactory.actions.store_data')], max_length=128),
        ),
        migrations.AlterField(
            model_name='form',
            name='post_to',
            field=models.CharField(blank=True, help_text=b'URL to which this form will be posted to. Leave blank to                         post back to original view.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='additional_validators',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
