# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0002_auto_20161014_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, default=256, null=True),
        ),
    ]
