# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0002_auto_20161003_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[(b'formfactory.tests.actions.dummy_action', b'formfactory.tests.actions.dummy_action'), (b'formfactory.actions.send_email', b'formfactory.actions.send_email'), (b'formfactory.actions.store_data', b'formfactory.actions.store_data')], max_length=128),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='additional_validators',
            field=models.CharField(blank=True, choices=[(b'formfactory.tests.validators.dummy_validator', b'formfactory.tests.validators.dummy_validator')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='actionparam',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Action'),
        ),
    ]
