# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0002_move_fields_to_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldgroup',
            name='show_title',
            field=models.BooleanField(default=False, help_text='Select this for Field group title to be displayed.'),
        ),
    ]
