# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0003_auto_20161017_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOrderThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short descriptive title.', max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('success_message', models.CharField(blank=True, max_length=256, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=256, null=True)),
                ('redirect_to', models.CharField(blank=True, help_text=b'URL to which this form will redirect to after processesing.', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WizardActionThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Action')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Wizard')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Wizard Action',
                'verbose_name_plural': 'Wizard Actions',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='redirect_to',
            field=models.CharField(blank=True, help_text=b'URL to which this form will redirect to after processesing.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='widget',
            field=models.CharField(blank=True, choices=[(b'TextInput', b'TextInput'), (b'NumberInput', b'NumberInput'), (b'EmailInput', b'EmailInput'), (b'URLInput', b'URLInput'), (b'PasswordInput', b'PasswordInput'), (b'HiddenInput', b'HiddenInput'), (b'DateInput', b'DateInput'), (b'DateTimeInput', b'DateTimeInput'), (b'TimeInput', b'TimeInput'), (b'Textarea', b'Textarea'), (b'CheckboxInput', b'CheckboxInput'), (b'Select', b'Select'), (b'NullBooleanSelect', b'NullBooleanSelect'), (b'SelectMultiple', b'SelectMultiple'), (b'RadioSelect', b'RadioSelect'), (b'CheckboxSelectMultiple', b'CheckboxSelectMultiple')], help_text='Leave blank if you prefer to use the default widget.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wizard',
            name='actions',
            field=models.ManyToManyField(through='formfactory.WizardActionThrough', to='formfactory.Action'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='forms',
            field=models.ManyToManyField(through='formfactory.FormOrderThrough', to='formfactory.Form'),
        ),
        migrations.AddField(
            model_name='formorderthrough',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Form'),
        ),
        migrations.AddField(
            model_name='formorderthrough',
            name='wizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Wizard'),
        ),
    ]
