# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-02 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0003_formfieldgroup_show_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='post_to',
        ),
    ]
