# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0003_auto_20161017_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOrderThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Form')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short descriptive title.', max_length=30)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WizardActionThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Wizard Action',
                'verbose_name_plural': 'Wizard Actions',
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[(b'formfactory.actions.login', b'formfactory.actions.login'), (b'formfactory.actions.wizard_done_step', b'formfactory.actions.wizard_done_step'), (b'formfactory.actions.send_email', b'formfactory.actions.send_email'), (b'formfactory.actions.store_data', b'formfactory.actions.store_data')], max_length=128),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='additional_validators',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='widget',
            field=models.CharField(blank=True, choices=[(b'TextInput', b'TextInput'), (b'NumberInput', b'NumberInput'), (b'EmailInput', b'EmailInput'), (b'URLInput', b'URLInput'), (b'PasswordInput', b'PasswordInput'), (b'HiddenInput', b'HiddenInput'), (b'DateInput', b'DateInput'), (b'DateTimeInput', b'DateTimeInput'), (b'TimeInput', b'TimeInput'), (b'Textarea', b'Textarea'), (b'CheckboxInput', b'CheckboxInput'), (b'Select', b'Select'), (b'NullBooleanSelect', b'NullBooleanSelect'), (b'SelectMultiple', b'SelectMultiple'), (b'RadioSelect', b'RadioSelect'), (b'CheckboxSelectMultiple', b'CheckboxSelectMultiple')], help_text='Leave blank if you prefer to use the default widget.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wizardactionthrough',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Action'),
        ),
        migrations.AddField(
            model_name='wizardactionthrough',
            name='wizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Wizard'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='actions',
            field=models.ManyToManyField(through='formfactory.WizardActionThrough', to='formfactory.Action'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='forms',
            field=models.ManyToManyField(through='formfactory.FormOrderThrough', to='formfactory.Form'),
        ),
        migrations.AddField(
            model_name='formorderthrough',
            name='wizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formfactory.Wizard'),
        ),
    ]
