# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0004_auto_20170117_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[(b'Formset', b'formset'), (b'Div', b'div')], default=b'formset', max_length=16)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfieldgroups', to='formfactory.FormFieldGroup')),
            ],
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formfactory.FormFieldGroup'),
        ),
    ]
