# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('formfactory', '0004_remove_form_post_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='model_choices_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='model_choices_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
