# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0005_added_enum_generic_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='additional_validators',
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator', models.CharField(choices=[], max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='formfield',
            name='additional_validators',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE,
                                    to='formfactory.Validator'),
        ),
    ]
