# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0006_additional_validator_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='additional_validators',
            field=models.ManyToManyField(blank=True, to='formfactory.Validator'),
        ),
    ]
