# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0007_additional_validators_can_be_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[], max_length=128)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='formfield',
            name='error_messages',
            field=models.ManyToManyField(blank=True, to='formfactory.CustomErrorMessage'),
        ),
    ]
