# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0008_custom_field_error_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='enable_csrf',
            field=models.BooleanField(default=True, help_text='Cross site request forgery protection may not be needed in all cases. Since it incurs a performance penalty you may wish to disable it.', verbose_name='Enable CSRF protection'),
        ),
    ]
