# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0009_form_enable_csrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_method', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customerrormessage',
            options={'verbose_name': 'Field error message', 'verbose_name_plural': 'Field error messages'},
        ),
        migrations.AddField(
            model_name='form',
            name='clean_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formfactory.CleanMethod'),
        ),
    ]
