# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0010_add_clean_methods_to_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='ajax_post',
            field=models.BooleanField(default=False, help_text='Hook for default submit handler to be overriden by JS.', verbose_name='Enable AJAX posting.'),
        ),
    ]
