# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0011_form_field_label_length_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='ajax_post',
            field=models.BooleanField(default=False, help_text='Hook for default submit handler to be overriden by JS.', verbose_name='Enable AJAX posting.'),
        )
    ]
