# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:54
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formfactory', '0013_auto_20170908_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='paragraph',
            field=simplemde.fields.SimpleMDEField(blank=True, help_text=b'Markdown for the formfactory ParagraphField and ParagraphWidget combination.', null=True),
        ),
    ]
